// Code generated by entc, DO NOT EDIT.

package ent

import (
	"gitlab.com/vund5/chatapp/ent/schema"
	"gitlab.com/vund5/chatapp/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescRoom is the schema descriptor for room field.
	userDescRoom := userFields[1].Descriptor()
	// user.DefaultRoom holds the default value on creation for the room field.
	user.DefaultRoom = userDescRoom.Default.(string)
	// userDescMsg is the schema descriptor for msg field.
	userDescMsg := userFields[2].Descriptor()
	// user.DefaultMsg holds the default value on creation for the msg field.
	user.DefaultMsg = userDescMsg.Default.(string)
}
